### ISSUE TITLE
Network issue

### ISSUE THREAD

**Issue by calex80** [hashtaginfosec/vagrantlab#2]
Hello, I am having this error installing the lab, any suggestion to fix it?

``The specified host network collides with a non-hostonly network!
This will cause your specified IP to be inaccessible. Please change
the IP or name of your host only network so that it no longer matches that of
a bridged or non-hostonly network.``

I tried to change it in Network properties but it does not work

![image](https://user-images.githubusercontent.com/58860205/222165314-ccb8d257-e31a-4aac-9c92-e5482421011c.png)

**Comment by hashtaginfosec** [comment]
Both bridged and host-only adapter are using 192.168.56.x range of IPs. I'd suggest doing a find replace on 192.168.56 in your local copy of this repo and change it to something else. I have hard coded IPs out of laziness :)

**Comment by calex80** [comment]
Thank you for your quick response, here is attached an example of the code in the VagrantFile, its actually listed on 192.168.56.x.

Is this what you mean?

![image](https://user-images.githubusercontent.com/58860205/222180081-7709ba04-6575-484f-a1bf-45e5e8cda6f4.png)

**Comment by hashtaginfosec** [comment]
Yes. Based on the error message in your original comment, your bridged interface and the host only network created by this repo are using same 192.168.56.x ranges. If you replace the ones in this report with something different (see https://github.com/hashtaginfosec/vagrantlab/search?q=192.168.56&type=code for where it exists), that should fix it.

**Comment by calex80** [comment]
Thank you, it works.

**Comment by calex80** [comment]
Quick question, this lab is still requiring only virtualbox? I would like to run it with vmware, is more flexible and stable. Any chance to?

**Comment by hashtaginfosec** [comment]
You can just change the Vagrant drive from virtualbox to vmware_desktop in VagrantFile. For example, replace the following:
```
    cfg.vm.provider "virtualbox" do |vb, override |
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
```
with following:
    ```
  config.vm.provider "vmware_desktop" do |v|
        v.gui = true
        v.vmx["memsize"] = "2048"
        v.vmx["numvcpus"] = "2"
```

See more here: https://developer.hashicorp.com/vagrant/docs/providers/vmware
